[package]
name = "rust-8"
version = "0.1.0"
authors = ["Jordan Werthman <jordanwerthman@gmail.com>"]
edition = "2018"

[dependencies]
env_logger = "*"
log = "0.4.6"
piston_window = "0.89.0"
rand = "0.6"

[lib]
name = "rust8"
